os:
  - windows
language: shell

install:
  - choco install -y lxrunoffline
before_script:
  - env | sort
  - export PATH=$ChocolateyToolsLocation/lxrunoffline:$PATH
  - lxrunoffline version
  - powershell -Command 'Get-ExecutionPolicy'
script:
  - wslconfig /l || true
  - |
    ## Install WSL distribution
    name=ubuntu1804
    curl -L -o "$name.tar.gz" "https://lxrunoffline.apphb.com/download/Ubuntu/bionic"
    LxRunOffline install -n $name -d "${LOCALAPPDATA}\WSL\$name" -f "$name.tar.gz"
  - wslconfig /l || true
